[project]
name = "cp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.2.3",
    "gtts>=2.5.4",
    "openai-whisper==20231117",
    "pydub>=0.25.1",
    "pygame>=2.6.1",
]
